# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Swensen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   I'm a Film Maker, Special Effects Guru, Part time nerd, and Full time geek.
   I write software and DJ a little on the side.
   Technology is a passion of mine. This is where I blog about it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexswensen.io" # the base hostname & protocol for your site
twitter_username: alexswens
github_username:  alexswensen

# Build settings
markdown: kramdown
