# Site
title:              Alexander Swensen
bio:                "I'm Alexander Swensen. I'm a full stack web developer based in Nashville. I sometimes write stuff here."
description:        "I'm Alexander Swensen. I'm a full stack web developer based in Nashville. I sometimes write stuff here."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://alexswensen.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   alexswensenio

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics: UA-39293631-3
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            I_amAlexSwensen
#facebook:
github:             alexswensen
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          alexanderswensen
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
hackernews:        alexswensen
twitch:            alexswensen

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

excerpt_separator: <!--more-->

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
